#!/bin/bash

#mouting all directory will be copy to github

Mount() {
    #run as sudo
    #/var/www
    sudo mount --bind /var/www/hivemq-mqtt-web-client  /home/pi/SH017/var/www/hivemq-mqtt-web-client
    sudo mount --bind /var/www/html /home/pi/SH017/var/www/html
    sudo mount --bind /var/www/rflink /home/pi/SH017/var/www/rflink
    sudo mount --bind /var/www/rfx433MHz /home/pi/SH017/var/www/rfx433MHz
    sudo mount --bind /var/www/seahu /home/pi/SH017/var/www/seahu
    sudo mount --bind /var/www/ser2net  /home/pi/SH017/var/www/ser2net
    #/opt
    sudo mount --bind /opt/owfs/ /home/pi/SH017/opt/owfs/
    sudo mount --bind /opt/rflink/ /home/pi/SH017/opt/rflink/
    sudo mount --bind /opt/rfx433MHz/ /home/pi/SH017/opt/rfx433MHz/
    sudo mount --bind /opt/seahu/ /home/pi/SH017/opt/seahu/
    #/etc
}

Umount() {
    #run as sudo
    #/var/www
    sudo umount /home/pi/SH017/var/www/hivemq-mqtt-web-client
    sudo umount /home/pi/SH017/var/www/html
    sudo umount /home/pi/SH017/var/www/rflink
    sudo umount /home/pi/SH017/var/www/rfx433MHz
    sudo umount /home/pi/SH017/var/www/seahu
    sudo umount /home/pi/SH017/var/www/ser2net
    #/opt
    sudo umount /home/pi/SH017/opt/owfs
    sudo umount /home/pi/SH017/opt/rflink
    sudo umount /home/pi/SH017/opt/rfx433MHz
    sudo umount /home/pi/SH017/opt/seahu
    #/etc
}

Update() {
    #update files and directores who not mount

    #/etc
    rm -R -d /home/pi/SH017/etc
    mkdir /home/pi/SH017/etc
    sudo cp /etc/rc.local /home/pi/SH017/etc/
    #/lib/systemd/system
    rm -R -d /home/pi/SH017/lib
    mkdir /home/pi/SH017/lib
    mkdir /home/pi/SH017/lib/systemd
    mkdir /home/pi/SH017/lib/systemd/system
    sudo cp /lib/systemd/system/beep.service /home/pi/SH017/lib/systemd/system/
    sudo cp /lib/systemd/system/graph_lcd.service /home/pi/SH017/lib/systemd/system/
    sudo cp /lib/systemd/system/lcd_menu.service /home/pi/SH017/lib/systemd/system/
    #/etc/init.d
    mkdir /home/pi/SH017/etc/init.d
    sudo cp /etc/init.d/rflink /home/pi/SH017/etc/init.d/
    sudo cp /etc/init.d/rfx433MHz /home/pi/SH017/etc/init.d/
    #network				(dhcpd.conf.orig is used by my scripts for create final dhcpcd.conf)
    sudo cp /etc/dhcpcd.conf.orig /home/pi/SH017/etc/
    #wifi
    # everything is generated by my or raspberry pi scripts
    #openvpn
    sudo cp -R /etc/openvpn /home/pi/SH017/etc/
    #ser2net
    sudo cp /etc/ser2net.yaml /home/pi/SH017/etc/
    #owfs
    sudo cp /etc/owfs.conf /home/pi/SH017/etc/
    #mosquitto
    sudo cp /etc/mosquitto/mosquitto.conf /home/pi/SH017/etc/mosquitto
    #rc.local
    sudo cp /etc/rc.local /home/pi/SH017/etc/
    #rflink
    sudo cp /etc/rflink.conf /home/pi/SH017/etc/
    #sudoers
    sudo cp /etc/sudoers /home/pi/SH017/etc/
    #apache
    sudo cp -R /etc/apache2 /home/pi/SH017/etc/
    #seahu
    sudo cp -R /etc/seahu /home/pi/SH017/etc/
    #domoticz
    sudo cp -R /etc/domoticz /home/pi/SH017/etc/

    #/home
    #/home/pi/examples
    rm -R -d /home/pi/SH017/home
    mkdir /home/pi/SH017/home
    mkdir /home/pi/SH017/home/pi
    sudo cp -R /home/pi/examples /home/pi/SH017/home/pi/
    #/home/pi/install_SH017.sh
    sudo cp -u /home/pi/install_SH017.sh /home/pi/SH017/home/pi/
    #/home/pi/domoticz
    sudo cp -R /home/pi/domoticz /home/pi/SH017/home/pi/


    #right
    #chmod -R /home/pi/SH017/etc/* o=r
    sudo find /home/pi/SH017/etc -type d -exec chmod o=rx {} +
    sudo find /home/pi/SH017/etc -type f -exec chmod o=r {} +

}

GitRemove() {
    #remove all git stops
    find . -type f | grep -i "\.git" | xargs rm
}

ListPkg() {
    #list of instaled pakages
    apt list --installed > /home/pi/SH017/list_intalled_packages.txt
}

case "$1" in
    mount)
	Mount
	;;
    umount)
	Umount
	;;
    update)
	Update
	;;
    gitRemove)
	GitRemove
	;;
    list)
	ListPkg
	;;
    *)
	SCRIPTNAME="${0##*/}"
	echo "Usage: $SCRIPTNAME {mount|umount|update|gitRemove|list}"
	;;
esac

exit 0