'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (paul.alfille@gmail.com)
'\"
'\" Device manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No warranty. None. Use at your own risk.
'\"
.TH DS2755 3  2003 "OWFS Manpage" "One-Wire File System"
.SH NAME
.B DS2755, DS2756
\- Multichemistry Battery Fuel Gauge
.SH SYNOPSIS
.SS Temperature Voltage, Current, Memory, and Switch.
.PP
.B 35
[.]XXXXXXXXXXXX[XX][/[
.B alarm_set/[volthigh|voltlow|temphigh|templow]
|
.B lock.[0-2|ALL]
|
.B memory
|
.B pages/page.[0-2|ALL]
|
.B PIO
|
.B sensed
|
.B temperature
|
.B vbias
|
.B vis
|
.B volt
|
.B volthours
|
.br
.B defaultpmod
|
.B pie0
|
.B pie1
|
.B rnaop
|
.B ios
|
.B uben
|
.B ovd
|
.B pmod
|
.B por
|
.B uven
|
.br
'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (paul.alfille@gmail.com)
'\"
'\" Program manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No warranty. None. Use at your own risk.
'\"
.B address
|
.B crc8
|
.B id
|
.B locator
|
.B r_address
|
.B r_id
|
.B r_locator
|
.B type
]]
.SS Thermocouple
.PP
.B 35
[.]XXXXXXXXXXXX[XX][/[
.B temperature
|
.B typeX/range_low
|
.B typeX/range_high
|
.B typeX/temperature
.SH FAMILY CODE
.PP
.I 35
.SH SPECIAL PROPERTIES
.SS alarm_set/templow alarm_set/temphigh
.I read-write, integer
.br
High and low alarm settings for
.I temperature
.SS alarm_set/voltlow alarm_set/volthigh
.I read-write, floating point
.br
High and low alarm settings for
.I volts
.SS lock.[0-2|ALL]
.I read-write, yes-no
.br
Lock any of the three eprom pages to prevent further writes. Apparently setting
.I lock
is permanent.
.SS memory
.I read-write, binary
.br
Access to the full 256 byte memory range. Much of this space is reserved or special use. User space is the
.I page
area.
.br
See the
.I DATASHEET
for a full memory map.
.SS pages/pages.[0-2|ALL]
.I read-write, binary
Three 32 byte areas of memory for user application. The
.I lock
property can prevent further alteration.
.br
NOTE that the
.I page
property is different from the common 
.I OWFS
implementation in that all of
.I memory
is not accessible.
.SS PIO
.I write-only, yes-no
.br
Controls the PIO pin allowing external switching.
.br
Writing "1" turns the PIO pin on (conducting). Writing "0" makes the pin non-conducting.
The logical state of the voltage can be read with the
.I sensed
property. This will reflect the current voltage at the pin, not the value sent to
.I PIO
.br
Note also that
.I PIO
will also be altered by the power-status of the
.I DS2670
See the datasheet for details.
.SS sensed
.I read-only, yes-no
.br
The logical voltage at the PIO pin. Useful only if the
.I PIO
property is set to "0" (non-conducting).
.br
Value will be 0 or 1 depending on the voltage threshold.
.SS temperature
.I read-only, floating point
.br
.I Temperature
read by the chip at high resolution (~13 bits). Units are selected from the invoking command line. See
.B owfs(1)
or
.B owhttpd(1)
for choices. Default is Celsius.
.br
Conversion is continuous.
.SS vbias
.I read-write, floating point
.br
Fixed offset applied to each
.I vis
measurement. Used for the
.I volthours
value. Units are in
.B Volts.
.br
Range \-2.0mV to 2.0mV
.SS vis
.I read-only, floating point
.br
Current sensor reading (unknown external resistor). Measures the voltage gradient between the Vis pins. Units are in
.B Volts
.br
The
.I vis
readings are integrated over time to provide the
.I volthours
property.
.br
The
.I current
reading is derived from
.I vis
assuming the internal 25 mOhm resistor is employed. There is no way to know this through software.
.SS volt
.I read-only, floating point
.br
Voltage read at the voltage sensor;. This is separate from the
.I vis
voltage that is used for
.I current
measurement. Units are
.B Volts
.br
Range is between 0 and 4.75V
.SS volthours
.I read-write, floating point
.br
Integral of
.I vis - vbias
over time. Units are in
.B volthours
.SH THERMOCOUPLE
.SS typeX/
.I directory
.br
Thermocouple circuit using the
.I  DS2755
to read the Seebeck voltage and the reference temperature. Since the type interpretation of the values read depends on the type of thermocouple, the correct directory must be chosen. Supported thermocouple types include types B, E, J, K, N, R, S and T.
.SS typeX/range_low typeX/ranges_high
.I read-only, flaoting point
.br
The lower and upper temperature supported by this thermocouple (at least by the conversion routines). In the globally chosen temperature units.
.SS typeX/temperature
.I read-only, floating point
.br
Thermocouple temperature. Requires a voltage and temperature conversion. Returned in globally chosen temperature units.
.br
Note: there are two types of temperature measurements possible. The
.I temperature
value in the main device directory is the reference temperature read at the chip. The
.I typeX/temperature
value is at the thermocouple junction, probably remote from the chip.
.SH OBSCURE PROPERTIES
.SS pmod por uven pie0 pie1 ios uben ovd rnaop
.I varies, yes-no
.br
Bit flags corresponding to various battery management functions of the chip. See the 
.I DATASHEET
for details of the identically named entries.
.br
In general, writing "0" corresponds to a 0 bit value, and non-zero corresponds to a 1 bit value.
.SS defaultpmod
.I read-write, yes-no
.br
Default power-on state for the corresponding properties.
.SH STANDARD PROPERTIES
'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (paul.alfille@gmail.com)
'\"
'\" Program manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No warranty. None. Use at your own risk.
'\"
.SS address
.SS r_address
.I read-only, ascii
.br
The entire 64-bit unique ID. Given as upper case hexadecimal digits (0-9A-F).
.br
.I address
starts with the
.I family
code
.br
.I r address
is the
.I address
in reverse order, which is often used in other applications and labeling.
.SS crc8
.I read-only, ascii
.br
The 8-bit error correction portion. Uses cyclic redundancy check. Computed from the preceding 56 bits of the unique ID number. Given as upper case hexadecimal digits (0-9A-F).
.SS family
.I read-only, ascii
.br
The 8-bit family code. Unique to each
.I type
of device. Given as upper case hexadecimal digits (0-9A-F).
.SS id
.SS r_id
.I read-only, ascii
.br
The 48-bit middle portion of the unique ID number. Does not include the family code or CRC. Given as upper case hexadecimal digits (0-9A-F).
.br
.I r id
is the
.I id
in reverse order, which is often used in other applications and labeling.
.SS locator
.SS r_locator
.I read-only, ascii
.br
Uses an extension of the 1-wire design from iButtonLink company that associated 1-wire physical connections with a unique 1-wire code. If the connection is behind a
.B Link Locator
the
.I locator will show a unique 8-byte number (16 character hexadecimal) starting with family code FE.
.br
If no
.B Link Locator
is between the device and the master, the
.I locator
field will be all FF.
.br
.I r locator
is the
.I locator
in reverse order.
.SS present (DEPRECATED)
.I read-only, yes-no
.br
Is the device currently
.I present
on the 1-wire bus?
.SS type
.I read-only, ascii
.br
Part name assigned by Dallas Semi. E.g.
.I DS2401
Alternative packaging (iButton vs chip) will not be distiguished.
.SH ALARMS
Temperature and voltage.
.SH DESCRIPTION
'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (paul.alfille@gmail.com)
'\"
'\" Program manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No warranty. None. Use at your own risk.
'\"
.SS 1-Wire
.I 1-wire 
is a wiring protocol and series of devices designed and manufactured
by Dallas Semiconductor, Inc. The bus is a low-power low-speed low-connector
scheme where the data line can also provide power.
.PP
Each device is uniquely and unalterably numbered during manufacture. There are a wide variety
of devices, including memory, sensors (humidity, temperature, voltage,
contact, current), switches, timers and data loggers. More complex devices (like
thermocouple sensors) can be built with these basic devices. There are also
1-wire devices that have encryption included.
.PP
The 1-wire scheme uses a single 
.I bus master
and multiple
.I slaves
on the same wire. The bus master initiates all communication. The slaves can be 
individually discovered and addressed using their unique ID.
.PP
Bus masters come in a variety of configurations including serial, parallel, i2c, network or USB
adapters.
.SS OWFS design
.I OWFS
is a suite of programs that designed to make the 1-wire bus and its
devices easily accessible. The underlying principle is to create a virtual
filesystem, with the unique ID being the directory, and the individual
properties of the device are represented as simple files that can be read and written.
.PP 
Details of the individual slave or master design are hidden behind a consistent interface. The goal is to 
provide an easy set of tools for a software designer to create monitoring or control applications. There 
are some performance enhancements in the implementation, including data caching, parallel access to bus 
masters, and aggregation of device communication. Still the fundamental goal has been ease of use, flexibility
and correctness rather than speed.
.SS DS2755 DS2756
The
.B DS2755 (3)
and
.B DS2756 (3)
are battery charging controllers similar to the
.B DS2751 (3)
except no internal resistor option and a larger EEPROM memory.
.PP
The
.B DS2756 (3)
adds suspend modes (
.I pie0 pie1
) to the
.B DS2755 (3)
.PP
A number of interesting devices can be built with the
.B DS2755 (3)
and
.B DS2756 (3)
including thermocouples. Support for thermocouples in built into the software, using the embedded thermister as the cold junction temperature.
.SH ADDRESSING
'\"
'\" Copyright (c) 2003-2004 Paul H Alfille, MD
'\" (paul.alfille@gmail.com)
'\"
'\" Program manual page for the OWFS -- 1-wire filesystem package
'\" Based on Dallas Semiconductor, Inc's datasheets, and trial and error.
'\"
'\" Free for all use. No warranty. None. Use at your own risk.
'\"
All 1-wire devices are factory assigned a unique 64-bit address. This address is of the form:
.TP
.B Family Code
8 bits
.TP
.B Address
48 bits
.TP
.B CRC
8 bits
.IP
.PP
Addressing under OWFS is in hexadecimal, of form:
.IP
.B 01.123456789ABC
.PP
where
.B 01
is an example 8-bit family code, and
.B 12345678ABC
is an example 48 bit address.
.PP
The dot is optional, and the CRC code can included. If included, it must be correct.
.SH DATASHEET
.br
http://pdfserv.maxim-ic.com/en/ds/DS2755.pdf
.br
http://pdfserv.maxim-ic.com/en/ds/DS2756.pdf
.SH SEE ALSO
.SS Programs
.B owfs (1) owhttpd (1) owftpd (1) owserver (1)
.B owdir (1) owread (1) owwrite (1) owpresent (1)
.B owtap (1)
.SS Configuration and testing
.B owfs (5) owfs.aliasfile (5) owtap (1) owmon (1)
.SS Language bindings
.B owtcl (3) owperl (3) owcapi (3)
.SS Clocks
.B DS1427 (3) DS1904 (3) DS1994 (3) DS2404 (3) DS2404S (3) DS2415 (3) DS2417 (3)
.SS ID
.B DS2401 (3) DS2411 (3) DS1990A (3)
.SS Memory
.B DS1982 (3) DS1985 (3) DS1986 (3) DS1991 (3) DS1992 (3) DS1993 (3) DS1995 (3) DS1996 (3) DS2430A (3) DS2431 (3) DS2433 (3) DS2502 (3) DS2506 (3) DS28E04 (3) DS28EC20 (3)
.SS Switches
.B DS2405 (3) DS2406 (3) DS2408 (3) DS2409 (3) DS2413 (3) DS28EA00 (3) InfernoEmbedded (3)
.SS Temperature
.B DS1822 (3) DS1825 (3) DS1820 (3) DS18B20 (3) DS18S20 (3) DS1920 (3) DS1921 (3) DS1821 (3) DS28EA00 (3) DS28E04 (3) EDS0064 (3) EDS0065 (3) EDS0066 (3) EDS0067 (3) EDS0068 (3) EDS0071 (3) EDS0072 (3) MAX31826 (3)
.SS Humidity
.B DS1922 (3) DS2438 (3) EDS0065 (3) EDS0068 (3)
.SS Voltage
.B DS2450 (3)
.SS Resistance
.B DS2890 (3)
.SS Multifunction (current, voltage, temperature)
.B DS2436 (3) DS2437 (3) DS2438 (3) DS2751 (3) DS2755 (3) DS2756 (3) DS2760 (3) DS2770 (3) DS2780 (3) DS2781 (3) DS2788 (3) DS2784 (3)
.SS Counter
.B DS2423 (3)
.SS LCD Screen
.B LCD (3) DS2408 (3)
.SS Crypto
.B DS1977 (3)
.SS Pressure
.B DS2406 (3) TAI8570 (3) EDS0066 (3) EDS0068 (3)
.SS Moisture
.B EEEF (3) DS2438 (3)
.SH AVAILABILITY
http://www.owfs.org
.SH AUTHOR
Paul Alfille (paul.alfille@gmail.com)
