#!/bin/sh
### BEGIN INIT INFO
# Provides:          Seahu
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service for PLC compuer Seahu SH017 this service emlation non exist beeper on lcd board of SH017
# Description:       Service for PLC compuer Seahu SH017. This service use beeper on base board to emulate not exist beeper on lcd board of SH017 (especialy in domoticz I2C IOexpander whose is use in LCD board is easy control )
### END INIT INFO


DAEMON="/opt/seahu/service_beep.py"

# default config
# no configuration options
ONFIG=""

. /lib/lsb/init-functions

name=`basename $0`
PIDFILE="/var/run/$name.pid"

case "$1" in
    start)
        echo "Starting $name"
	#start-stop-daemon --start --verbose --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON
	start-stop-daemon -S -x $DAEMON -b -C -v -m -p $PIDFILE -- $CONFIG | logger -t $name &
	;;
    stop)
    	echo -n "Stopping $name."
	#pkill -P `cat $PIDFILE`
	start-stop-daemon -K -x $DAEMON -p $PIDFILE --remove-pidfile
	;;
    restart)
	echo -n "Restarting $name."
	$0 stop
	$0 start
	;;
    status)
	start-stop-daemon -T -x $DAEMON
	;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0