#!/bin/sh
### BEGIN INIT INFO
# Provides:          Seahu
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $lcd_menu
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Service enable print to graph LCD
# Description:       Service enable print to graph LCD
### END INIT INFO


DAEMON="/opt/seahu/service_graph_lcd.py"

# default config
# no configuration options
ONFIG=""

. /lib/lsb/init-functions

name=`basename $0`
PIDFILE="/var/run/$name.pid"

case "$1" in
    start)
        echo "Starting $name"
	#start-stop-daemon --start --verbose --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON
	start-stop-daemon -S -x $DAEMON -b -C -v -m -p $PIDFILE -- $CONFIG | logger -t $name &
	;;
    stop)
    	echo -n "Stopping $name."
	#pkill -P `cat $PIDFILE`
	start-stop-daemon -K -x $DAEMON -p $PIDFILE --remove-pidfile
	;;
    restart)
	echo -n "Restarting $name."
	$0 stop
	$0 start
	;;
    status)
	start-stop-daemon -T -x $DAEMON
	;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0