#!/bin/bash

help () {
	echo "HELP:"
	echo "-----"
	echo "-m mac (chnage do any effect)"
	echo "-i static ip"
	echo "-n static netmask"
	echo "-g static getway"
	echo "-d static dns"
	echo "-I dhcp (1=dhcp 0=static)"

	echo "-h help"
}

netmask2cidr () {
	local i= len=
	local IFS=.
	for i in $1; do
	while [ ${i} != "0" ]; do
		len=$((${len} + ${i} % 2))
		i=$((${i} >> 1))
	done
	done
	echo "${len}"
}

# first get actual values
#------------------------
net_seting=$(/opt/seahu/getNetSeting.sh)
echo "-- Print actual values: --"
for var_name in mac actual_ip actual_netmask actual_gateway actual_dns static_ip static_netmask static_gateway static_dns dhcp
    do
	line=$(echo "$net_seting" | grep ^$var_name:)
	#echo "line:"$line
	eval "$var_name"=${line#*:} # separe all after :      etc. mac:dc:a6:32:e3:5c:c6 get dc:a6:32:e3:5c:c6
	echo $var_name ${!var_name}
    done
#mac=$(echo "$wifi_seting" | sed -n '1p')
#static_ip=$(echo "$wifi_seting" | sed -n '2p')
#static_netmask=$(echo "$wifi_seting" | sed -n '3p')
#static_gateway=$(echo "$wifi_seting" | sed -n '4p')
#static_dns=$(echo "$wifi_seting" | sed -n '5p')
#dhcp=$(echo "$wifi_seting" | sed -n '6p')

#replace actual values by new values by command arguments
#--------------------------------------------------------
while getopts m:i:n:g:d:I:h flag
do
    case "${flag}" in
	m) mac=${OPTARG};;
	i) static_ip=${OPTARG};;
	n) static_netmask=${OPTARG};;
	g) static_gateway=${OPTARG};;
	d) static_dns=${OPTARG};;
	I) dhcp=${OPTARG};;
	h) help;;
	\?) echo "Invalid option: $flag" 1>&2
	    help
	    ;;
	:) help;;
    esac
done
cidr=$(netmask2cidr "$static_netmask") # conver netmask do number etc. 255.255.255.0 to 24


# print new values
#------------------
echo "-- Print new values: --"
echo "mac: $mac"
echo "static_ip: $static_ip"
echo "stati_ netmask: $static_netmask"
echo "cidr: $cidr"
echo "static_gateway: $static_gateway"
echo "static_dns: $static_dns"
echo "dhcp: $dhcp"

# DO IT
#---------------------------
#/etc/dhcpc.conf # if need set static IP address or delete wlan0 entry
file=/etc/dhcpcd.eth0.conf
echo "" > $file
echo "#--- Seahu Wi-Fi config ---" >> $file
if [ "$dhcp" = "1" ] ; then	# dhcp
    echo "" > $file
    echo "#--- Seahu Net config ---" >> $file
    echo "" >> $file
    echo="# interface eth0 use auto dhcp cofigure" >> $file
    echo "# interface eth0" >> $file
    echo "# static ip_address=$static_ip/$cidr" >> $file
    echo "# static routers=$static_gateway" >> $file
    echo "# static domain_name_servers=$static_dns" >> $file
    echo "" >> $file
else 				# static
    echo "" > $file
    echo "### Do not edit. This part is generated by /opt/seahu/setWifiSeting.sh ###" >> $file
    echo "# interface eth0 use static setting" >> $file
    echo "interface eth0" >> $file
    echo "static ip_address=$static_ip/$cidr" >> $file
    echo "static routers=$static_gateway" >> $file
    echo "static domain_name_servers=$static_dns" >> $file
    echo "" >> $file
fi

cat /etc/dhcpcd.conf.orig > /etc/dhcpcd.conf
cat /etc/dhcpcd.eth0.conf >> /etc/dhcpcd.conf
cat /etc/dhcpcd.wlan0.conf >> /etc/dhcpcd.conf


# restart dhcp client service
systemctl stop dhcpcd
ip addr flush dev eth0
systemctl start dhcpcd
